name = "pew-ingest"
main = "src/index.ts"
compatibility_date = "2026-03-01"
workers_dev = true

[[routes]]
pattern = "pew-ingest.worker.hexly.ai"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "pew-db"
database_id = "5c00ebbf-a0ed-49d9-a64f-5712c272e96f"

# ---------- Test environment ----------
[env.test]
name = "pew-ingest-test"

[[env.test.d1_databases]]
binding = "DB"
database_name = "pew-db-test"
database_id = "aa08a894-6a65-4baf-b756-2e611dff437d"

[[env.test.routes]]
pattern = "pew-ingest-test.worker.hexly.ai"
custom_domain = true
